### ISSUE TITLE
Process of PDBbind crystal pose

### ISSUE THREAD

**Issue by zhuhui-in** [zjujdj/InteractionGraphNet#1]
When I tried to reproduce the result of the paper, I met some problems.
The graph of PDBbind crystal structure is generated by extracting 10A pocket with chimera as docked pose or just using the _pdbcode_pocket.pdb_ file provided by PDBbind.
Besides, RDKIT is failed to read some sdf ligand file, how to solve it?
Thank you a lot!

**Comment by zjujdj** [comment]
@zhuhui-in 
hello, sorry for this late reply.

i also encountered  the probelm you describled. To be honest. many files provided by the PDBBind official cannot be processed directly using RDlit. I processed them firstly using Protein_Preparation_Wizard module in Schrödinger, and then using RDkit, if still encountered  such probelm, i gave up those data directly.

**Comment by Xinxinatg** [comment]
@zjujdj Hi thanks for your wonderful work! May I ask whether it is possible to get the preprocessed data as you used in the manuscript? I just got the access to Schrödinger suite, but might take a while to familarize myself with the using. It would be really helpful that you can provide the preprocessed data first then I can have a first hand knowledge of how the training should be like.

**Comment by zjujdj** [comment]
@Xinxinatg sure,but how can i send it to you?

**Comment by Xinxinatg** [comment]
@zjujdj  thanks for your reply! would you mind uploading to any online drive which would be convenient for you to upload the file?

**Comment by zjujdj** [comment]
@Xinxinatg ,could get touch with me through the email: 3500400766@qq.com. i am afraid of you cannot understand the files easily. thx.

**Comment by Xinxinatg** [comment]
@zjujdj sure thanks! Just sent you the email
