### ISSUE TITLE
about virtual screening model

### ISSUE THREAD

**Issue by wantyUtry** [zjujdj/InteractionGraphNet#2]
Dear zjujdj,

Thanks for providing such an interesting script for the scoring, 

Could you write a simple tutorial for how to train VS models, it looks like the methods in the example are not suitable for VS model training

Hope to receive your reply!

**Comment by zjujdj** [comment]
@wantyUtry 
hello, sorry for this late reply. i am very busy recently, and i guess i'll post the ign vs training example a few weeks later, but the excat time has no guarantee.

**Comment by zjujdj** [comment]
@wantyUtry VS model trianing is similar to the binding affinity model training, just change the target values, and when the data volume is very big, i suggest you use multi gpu training. thx

**Comment by wantyUtry** [comment]
Do you mean using the same script to train the model? if yes, may I know how to set the label value for each complex

Hope to receive your reply soon

**Comment by zjujdj** [comment]
@wantyUtry ，yes, you can manage to do it using the same scripts. as for the label setting, i suggest you to refer to the ign paper, three datasets were coevered for vs modeling training in the paper,namely dud-e, dekois2.0 and lit-pcba. for them, decocy was set as 0, active was set as 1.
