### ISSUE TITLE
Need Your Kind Guidance

### ISSUE THREAD

**Issue by SyedKumailHussainNaqvi** [zjujdj/InteractionGraphNet#3]
Hi @zjujdj ,
I am currently involved in the curation of the CAMP dataset. However, I have encountered some challenges along the way. I kindly request your guidance and assistance regarding these issues. Your expertise and support would be greatly appreciated.

Thank you for your attention and prompt response. I look forward to hearing from you soon.

**Comment by zjujdj** [comment]
@SyedKumailHussainNaqvi 
Hi, 
what is CAMP dataset? and what issues you have encountered?

**Comment by SyedKumailHussainNaqvi** [comment]
@zjujdj 
Thanks you so much for your Kind Reply.
CAMP is a Convolutional Attention-based Neural Network for Multi-level Peptide-protein Interaction Prediction. this is github link of CAMP https://github.com/twopin/CAMP . 
I came across your question on the CAMP GitHub page regarding so  I am seeking your assistance in this matter. I hope that you are able to provide the help I need in this regard.
![CAMP](https://github.com/zjujdj/InteractionGraphNet/assets/125442863/d2160a2a-e3b5-4537-b662-ed8bd91f2673)

**Comment by SyedKumailHussainNaqvi** [comment]
I am currently experiencing a challenge with the target-mapping stage. Specifically, after generating an alignment_result file using the An SIMD Smith-Waterman C/C++ method, I encountered an error when attempting to pass this file to the target-mapping step.

 108                 target[name]=seq
    109     return target
--> 110 peptide_resolution_dict=get_result_dict()
    111 pdb_uniprot_map=get_pdb_to_uniprot_map(peptide_resolution_dict)
    112 query_residues=get_query_residue()

Input In [47], in get_result_dict()
     16         seq_target, seq_query, align = '', '', ''
     17     else:
---> 18         seq_target += line.split('\t')[1]
     19         #print('seq_target',seq_target)
     20 elif i%4 == 1:

IndexError: list index out of range

Kindly Help and guide me in this regards.
[alignment_result.txt](https://github.com/zjujdj/InteractionGraphNet/files/11935219/alignment_result.txt)

**Comment by zjujdj** [comment]
@SyedKumailHussainNaqvi 
Hi, why don't you directly ask the first author? To be honest, i forget the problem you mentioned. i run camp model a year ago, it's been a long time!

**Comment by SyedKumailHussainNaqvi** [comment]
Hi,
I have attempted to reach out to the first author of the CAMP Model via email and GitHub, but unfortunately, I have not received a response. 
Consequently, I am turning to you with the hope that you might be able to assist me in this matter. While I understand that your familiarity with the CAMP model may have diminished over time, 
I am curious to know if you were involved in creating the dataset for the model during that period when you compiled the CAMP model?

Thank you for considering my request.

**Comment by zjujdj** [comment]
@SyedKumailHussainNaqvi 
To be honest, the dateset preparation of camp model is very complicated with the need of many different softwares. I seem to remember that I also didn't succeed in creating the dataset. Finally, i suggested that you can contact with the corresponding author: https://iiis.tsinghua.edu.cn/zengjy/

**Comment by SyedKumailHussainNaqvi** [comment]
@zjujdj I acknowledge the validity of your statement regarding the arduous nature of preparing the dataset for the CAMP model. For the past three months, I have diligently worked on curating the dataset for my foundational paper on CAMP, as it serves as the cornerstone of my research. While significant progress has been made, I have unfortunately encountered a hurdle that has hindered my progress.

It has come to my attention that resolving the issue in the target-mapping stage can potentially be achieved by recalling the precise input format required for the alignment_result file. I have made attempts to utilize both the C/C++ and Python versions of the SIMD Smith-Waterman tool, yet it appears that the alignment_result generated by either version does not align appropriately with the anticipated input format for the target-mapping stage.

if you remember about input format of alignment_result file then the error of target-mapping stage can be removed.
I will be highly appreciated your kind guidance and consideration.

**Comment by zjujdj** [comment]
@SyedKumailHussainNaqvi 
Hi, 
sorry for the late reply.. i rellay don't remember the thing you mentioned above...email the corresponding author mybe the best workaround, i think.

**Comment by SyedKumailHussainNaqvi** [comment]
@zjujdj 
So Sorry for lateness, Thanks a lot for your kind guidance and suggestion. I try my best to reach corresponding author.
Again Bundle of Thanks.

**Comment by BattlePuppy** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
afterhill, @mikehotel, @hide2, @rthorpe, @nulldataset, @KyleTang, @whosexx, @vae520283995, @patrickocoffeyo, @Xerosigma, @Asta1986, @sbedell, @zerotask17, @atmos1001, @ClaudeLiang, @wmcmurray, @degjeg, @mrtavat, @OrdinaryCarrot16, @Teqqles, @PJGitHub10, @degan, @SuperSkidder, @edward-tes, @autumn84, @brucewillis88, @polluxx, @ruralant, @BunsDev, @qprimed, @coid, @originated, @0x00031337, @custompointofview, @nieldm, @iongchun, @detizzled, @synsun, @Halama, @Mayankvlog, @moondisco, @r-o-g-e-r-y-a-n-g, @faint32, @qinix, @takuan-osho, @seven1oe, @xmotomatt, @yanpozka, @indrajithbandara, @daann1lWillKre, @hardcpp, @vinceramcesoliveros, @sawatani-stone, @WalaceProstituto, @ykymd, @cwsamuelson, @supersonicclay, @WorldofOpenDev, @nanoac, @HiTECNOLOGYs, @brycedev, @harmankang, @makevoid, @luokailiang, @daxxog, @skyz319, @hugomarquez, @Jonovono, @gonsuke, @xiaoleigua, @jake100, @gpearson100, @ethanliew, @daraosn, @lai3d, @1688apps, @vdt, @davinian, @Drinkler, @Swaagie, @KleeTaurus, @CaptThomas, @raizor, @alixaxel, @Meler-Andy, @jordaniellis, @deveopsgenuis, @bsquidwrd, @jsuper, @nukesk3, @andrewerrico, @fkztw, @rictorres, @juliandavidmr, @harrywynnwill, @alexpablo, @TheKhanj, @Oziomajnr, @kseoRacZo, @jeongyy, @kevinmgyu, @xoan, @thomasplevy, @darshil, @wgiger, @zfarbp, @Trogdor23c, @lxm1117, @YingCGooi, @ajacquelin, @Cxihu, @AbhiAgarwal, @elimisteve, @ionaryu, @adamtache, @seanblonien, @mervinchan, @caihua, @teredin, @ygalvao, @corstian, @justyns, @manuasir, @blakejakopovic, @c0c41n3, @dwongdev, @timothyklim, @coinnotifications, @joeZheng3, @lokgie, @waar19, @kdbcinco, @ttimot24, @marcuswikstrom, @abood3lessa, @lux10n, @Skparab1, @dzhshf, @vivekpn, @liquidzym, @rkoichi, @sTorro, @bmjjr, @tdawger, @themeadery, @ReisMiner, @mi6e4ka, @kakaLQYuvim, @mrpeski, @erickmerick, @wbarobinson, @LB--, @mshkdm, @Zandy, @gtt116, @yguy08, @Foorasteroo, @bede, @keeganskeate, @codehunt023, @kshokhin, @hardlinepros, @bernestoalberto, @yangwao, @jgarte, @TRXDOGE, @honood, @JihoChoi, @Lucas-Developer, @prodigeni, @rbute, @abstream, @jbouhier, @eclipticrick, @fan-h, @0xOutOfGas, @Stankye, @otharwa, @bluecoiner, @shlokgilda, @shaynair, @jamlfy, @Lesmiscore, @whiteBeer, @maqz9999, @marcopolello, @LaceySam, @alexchwoj, @lmacken, @zhulin0001, @ruscoe, @oscarrock, @aproios, @yutelin, @yarwelp, @scientist2009, @arshinalbabmcsage, @shakurov, @GusevVasily, @kthomas, @avallejom, @Saka7, @Marti2602, @irazasyed, @71ae, @gituser, @atmshop, @git-user-2, @mikeumus, @jonnyplankstrykare, @DoCmAL1, @starwill, @nvhoang, @Mujaddadi, @pcpppcpppcpp, @lokisama, @x2q, @Aspsine, @unixorn, @Dopedash, @ryanjdillon, @RusAlex, @missword2012, @vietbaoa4htk, @yubingxing, @hardlinepros, @mangobug, @femithedev, @Trina0224, @vamdt, @AarbozT, @justsml, @MonNomSontPasUtile, @vincenzopalazzo, @meyerjoachim, @sirluky, @coasterzu, @changtailiang, @Astraeux, @visorq, @becomejavasenior, @eugeneiiim, @shenghub, @vgel, @nkavian, @Freccia
